### ISSUE TITLE
TODO: Frontend

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#3]
- [ ] Category drop down
  - [ ] Admin Tools
  - [ ] Developer Tools
  - [ ] Chat
  - [ ] Economy
  - [ ] Protection
  - [ ] Games
  - [ ] Role Playing
  - [ ] World Management
  - [ ] Gameplay
  - [ ] Miscellaneous
  - [ ] More/Less?
- [ ] Latest/New/Hot/Top Sorting
- [ ] Search
- [ ] Developer pages
- [ ] Team pages
- [ ] Color code versions
- [ ] Channel filtering
- [ ] Embedded Discourse discussion
- [ ] Sign up page
- [ ] Login page
- [ ] Docs editor
- [ ] Project manager
- [ ] Channel editor
- [ ] Flag reason popup
- [ ] More...?

**Comment by ryantheleach** [comment]
User submittable tags rather then categories maybe?

**Comment by windy1** [comment]
No I think the categories should be static or else you just get a mess of 100s of tags which is basically as good as no tags at all.

**Comment by ryantheleach** [comment]
https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

**Comment by ryantheleach** [comment]
Saw that you closed this, I'm guessing you have finished it and no longer want help with the frontend? 

I'd been slowly working on it.. https://ryantheleach.github.io/ore-mockup/

**Comment by windy1** [comment]
More that the frontend has diverged from this TODO list quite a bit since I opened it. I always welcome contributions but I kind of like the direction it's going in currently TBH.

**Comment by ryantheleach** [comment]
> I kind of like the direction it's going in currently TBH.

referring to the mockup, or the current play-ore master? I tried checking out master to have another look, but I'm not managing to resolve the sbt dependencies anymore. You may need to add some resolvers.

**Comment by windy1** [comment]
The one on master and oh yeah sorry I temporarily disabled the sponge repo for testing since I have plugin-meta installed locally. If you uncomment it in the build.sbt file it should work fine.

**Comment by ryantheleach** [comment]
I uncommented the sponge-repo line but I'm still having issues,are all of the library dependencies really found in only those 2 repositories?

**Comment by windy1** [comment]
Should be, yeah. Can you post your log file?
