### ISSUE TITLE
Staff-side Improvements

### ISSUE THREAD

**Issue by mbax** [SpongePowered/Ore#329]
* [x] 1.  Approval Queue self-assignment locking
Goal is to avoid two staff reviewing the same thing. Prior to allowing a user to 'approve' a file, require them to click a button to mark the file as being 'under review.' When clicked, checks against latest before updating for the user. (#351)
    * "Are you sure?" prompt to allow override to someone else.
    * Automatically (process on next queue load?) expire lock-out if locked for longer than some configured period of time (30 minutes? hour? Doesn't have to be too short)
    * Cannot mark more than a configurable quantity (5? 10?) of files at once. 

* [x] 2. Display (to staff) who approved a file and when it was approved on the file's page. (#351)

* [x] 3. Display, if present, the approval history of users on a page accessible from their profile. 

* [x] 4. Staff page. List who is staff specifically on Ore, for convenience (easy jump to request number three above). (#529)

* [ ] 5. Approval stats on a page for staff viewing.
    * [x] Approvals per day. (#381)
    * [x] Flags handled per day (#381)
    * [x] Submissions per day. (#381)
    * [x] Flags created per day (#381)
    * [ ] Recent staff activity (selectable time frames like "last week" "last month" or just a "from: to:")

* [x] 6. Ability to make an entire project page unviewable to non-staff (still viewable by members of the project so they can fix problems and flag it for approval). For situations of pages not compliant with the guidelines to the point they need to be taken down

* [x] 7. Ability for staff to view a list (sortable and searchable) of projects in the above unviewable state. 
  
* [x] 8. Staff notes on projects, accessible from the project page. Tracked by user writing them. This way I could say "PM'd 9 Jan 2018 about guidelines violation" or something. (#391)

**Comment by Ewoutvans** [comment]
> 3. Display, if present, the approval history of users on a page accessible from their profile.

> 4. Staff page. List who is staff specifically on Ore, for convenience (easy jump to request number three above).

Public or private (staff only) pages?

**Comment by mbax** [comment]
I'd say both staff only. The staff listing could be considered for being public later, but I figure the listing on the organization is enough for that.

**Comment by Ewoutvans** [comment]
@mbax is number 8 only visible by staff or can the project owner also see them?

**Comment by kashike** [comment]
I'd say staff only.

**Comment by mbax** [comment]
All of these are staff only.

**Comment by JBYoshi** [comment]
I think #429 fixes point 6, although I'm not 100% sure.

**Comment by mbax** [comment]
I'd like this one done for 1.6.0:

Ability for staff to search by project state (visible, new, needs changes, deleted) in the search.

**Comment by phase** [comment]
Point 4 has been added with #529.
