### ISSUE TITLE
New OCD Issue : Milestone 1.6

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#368]
- [x] The terms button on the footer still leads nowhere. https://github.com/SpongePowered/Ore/pull/419
- [x] Alternatively ore should display the sponge or minecraft version targetted by the version in the versions page list.
- [x] Uploading a new version of a plugin is giving a 500 error [fixed?](https://github.com/SpongePowered/Ore/issues/195#issuecomment-271160966)

**Comment by ryantheleach** [comment]
I've created issues, but I've not yet split them as I'm awaiting feedback from people while it's easier to view them as one list.

**Comment by phase** [comment]
go ahead and split these up

**Comment by felixoi** [comment]
I think all of these are fixed in master.
