### ISSUE TITLE
New OCD Issue : Milestone 1.7

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#369]
- [ ] you cannot search for orgs
- [ ] Orgs should have the ability to have multiple owners
- [x] Cannot add yourself as a developer of a project your organization owns.
- [ ] The ability to Edit the title of a version so that it can be more descriptive (eg. `8.2.0 for Sponge 6.0.0` rather than just `8.2.0`)
- [x] Pressing the back button when at a latter stage of creating a new project takes you all the way back to the beginning and forgets everything you entered, I would expect it to just return you to the previous section with the information you entered still there.

**Comment by Katrix** [comment]
Moved to minor issues list
