### ISSUE TITLE
Notifications 

### ISSUE THREAD

**Issue by Ewoutvans** [SpongePowered/Ore#384]
- [x] Give notification if version gets approved of project (#367)
- [x] Don't give notifications of plugin upload if uploaded the plugin (#367)
- [x] Redesign notification page (its broken on mobile)
- [ ] Give notifications to owners of organisation if someone accepts / declines 
- [ ] Give notification to owner of project when admin changed a page (or made a page invisible #329)

Anything I'm missing?
I'll be working on this if I have time this week

**Comment by malte-laukoetter** [comment]
It might also be interesting to add Push support to the notifications so it's not necessary to open up ore to know if there are any new notifications: https://developers.google.com/web/ilt/pwa/introduction-to-push-notifications
