### ISSUE TITLE
TODO: v1.0.0-BETA

### ISSUE THREAD

**Issue by windy1** [SpongePowered/Ore#4]
## Official Ore Backend TODO List
- [x] Data structures
  - [x] `Project`
    - [x] has `Channel`s
      - [x] has `Version`s
    - [x] has `Author`s
  - [x] `Author`
    - [x] `Dev`
    - [x] `Team`
      - [x] has `Dev`s
- [x] Database integration (~~MySQL~~ PostgreSQL)
  - [x] [Slick](http://slick.typesafe.com/doc/3.1.1/) setup
  - [x] Evolutions integration
  - [x] Slick integration with models
- [x] Authentication / Authorization
  - [x] Single-sign-on (SSO)
  - [x] Update views based on authorization / permissions
- [x] Uploads
  - [x] Basic plugin uploading
  - [x] Better file validation
    - [x] ~~Check meta file against plugin annotation~~ Annotation is ignored by Sponge if meta file is present
  - [x] Allow ZIP Archive bundles with plugin JAR in top level
  - [x] Add version to existing project
- [x] Project management
  - [x] Recommended download (main download link)
  - [x] ~~Change description~~ Version level descriptions only
  - [x] Create
  - [x] Rename
  - [x] Delete
  - [x] ~~Add Team~~ Moved to later release
  - [x] Add Developer
  - [x] ~~Roles~~ Moved to later release
  - [x] ~~Permissions~~ Moved to later release
  - [x] New version
  - [x] Set category
- [x] Statistics
  - [x] Views
  - [x] Downloads
  - [x] Starred
- [x] Channel management
  - [x] Color coded
  - [x] Max channels per project: 5?
  - [x] No duplicate colored channels
- [x] ~~Team management~~ Moved to later release
  - [x] Add/remove members
  - [x] ~~Permissons~~ Moved to later release
  - [x] ~~Roles~~ Moved to later release
  - [x] Project list
  - [x] ~~Activity feed~~ Moved to later release
  - [x] Team info
  - [x] Starred
- [x] Developer management
  - [x] ~~Create/disband team~~ Moved to later release
  - [x] Project list
  - [x] ~~Activity feed~~ Moved to later release
  - [x] Developer info
  - [x] Starred
- [x] Docs editing
  - [x] Markdown editor (3rd party library?)
  - [x] Validation
  - [x] Max pages per project: 10?
- [x] Project flagging
  - [x] Reason
  - [x] Moderation queue
- [ ] Sorting algorithms
  - [x] Latest: Recently discussed and/or updated
  - [x] New: Recently created
  - [x] ~~Hot: Recently popular~~ later
  - [x] Top: Most popular
- [x] Discourse integration
  - [x] Embedded discussion from forums
- [x] Pagination
  - [x] Projects
  - [x] Versions
- [x] More...?

**Comment by lukegb** [comment]
Suggestions:
- Organisation support entirely can be put off until later, as long as the groundwork is there (which it is)
- Some sort of resource control is probably necessary at this point, but it can probably just be GitHub-style collaborators (just add someone and they have permission to upload files, given that's basically the only feature)
- Statistics are hard. Don't worry too much about displaying them for now, but do collect them.

**Comment by lukegb** [comment]
(basically main Ore died because it caught a bad case of feature creep and then everyone got bored of implementing things on a product noone was using)

**Comment by kashike** [comment]
`Starred` -> `Stars` on homepage
