### ISSUE TITLE
Tracking issue for splitting up bootstrap 4 branch

### ISSUE THREAD

**Issue by felixoi** [SpongePowered/Ore#730]
Steps to go:
- [x] Port global layout changes (@felixoi, #731) 
- [ ] Port setting page changes (@felixoi)
- [x] Port new project/version creation (need help)

Maybe:
- [ ] Port review queue changes
