### ISSUE TITLE
State Of Sponge suggestions.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/Ore#86]
- [ ] ~~ryantheleach: Windy, can you add a tab for delvelopers when you do the maven repo stuff, that has the dependency and repo information to copy into cbt sbt maven gradle? #409~~
- [ ] ~~ryantheleach: sub forums for plugins? Often on dev bukkit people would share scripts and configs in a specific subforum #410~~
- [ ] ~~octo_byte_: Do you think there could be a way Ore can pickup on the docs file from the README.md on GitHub? (#87)~~

```
VcSaJen: What about linking to GitHub release/Bintray page from Ore? Will it be forbidden in future?
Lasercar7: directly pulling readmes from github would be awesome
windy973: VaSaJen: The whole idea is that the downloads are hosted on ore. this is important so we can track downloads and other statistics. Additionally, you can grab releases via the api

Ryan: there was something about pulling issues / posting issues back and forth that I missed.
```
- [ ] MeronatOfficial: Yeah, will there be sub-categories?

```
Socratic_phoenix: must be tags...
m0pt0pmatt: Or no catagories
m0pt0pmatt: Just recommended tags
octo_byte_: Tags are good for SEO too, so random ppl finding the project through Google
doubtingreality: I agree with Windy
doubtingreality: there should be separation between tags and categories
doubtingreality: categories should limit the scope of a plugin, aka "main" topic of the plugin
doubtingreality: while tags should expand on the properties of the plugin
MeronatOfficial: Yeah and the tags could be found through the search bar rather than the side coloumn.
MeronatOfficial: column*
doubtingreality: even tag cloud, search by tag popularity, etc is cool
doubtingreality: but tags are also dynamic; something that people should be able to add when necessary, while categories are mostly static terms
```
- [x] How do you tell the difference between sponge Plugins / Forge mods on Ore.

**Comment by ghost** [comment]
Created mine in #87

**Comment by windy1** [comment]
I don't quite understand the first one, the maven integration will use https://repo.spongepowered.org. Interesting thought for the second one. Thoughts on that @Zidane?

As far as categories go I think implementing some kind of tag system (not unlike stackoverflow) would be a good solution.

**Comment by ryantheleach** [comment]
![image](https://cloud.githubusercontent.com/assets/141554/14939208/b117f6dc-0f7b-11e6-9d0c-ee5aee1f01f0.png)

**Comment by windy1** [comment]
Ah I see what you mean now, yeah that would be neat.

**Comment by windy1** [comment]
@Zidane Thoughts on giving each project it's own forum category?

**Comment by parlough** [comment]
I think that maven repo feature would be great. I am planning on having an API for my Guilds plugin and a nice way for people to switch between the different build systems's format would be pretty useful. It could go along with certain versions of the plugin somehow, just in-case the API has changed with that release.

**Comment by ryantheleach** [comment]
Each of these should be fleshed out into their own issues and this list closed.

**Comment by ryantheleach** [comment]
@Ewoutvans @phase @felixoi @windy1  Do you feel like the current tag / category system fulfills peoples feedback above?

**Comment by felixoi** [comment]
I think so. Categories are implemented like they suggested and we decided against giving users the opportiunity to add tags by themself. Tags like the sponge version are added automatically.
